name: Build develop tag with Maven

on:
  push:
    tags:
      - 'rc-*'

jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'push'

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn --batch-mode package

    - name: Checkstyle Analysis
      run: mvn checkstyle:check

    - name: SpotBugs Analysis
      run: mvn spotbugs:check

    - name: Testing with Maven
      run: mvn test

    - name: Package build
      run: zip -r "${{ github.ref_name }}.zip" target/*.jar

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.ref_name }}
        path: "${{ github.ref_name }}.zip"
