name: Promote to Release Candidate

on:
  push:
    tags:
      - 'rc-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Resolve dependencies
      run: mvn --batch-mode dependency:resolve

    - name: Build with Maven
      run: mvn --batch-mode verify

    - name: Run Checkstyle
      run: mvn checkstyle:check

    - name: Run unit tests
      run: mvn test

    - name: Package the application
      run: mvn package

    - name: Create release artifact
      run: |
        VERSION=${GITHUB_REF##*/}
        mkdir -p release
        cp target/*.jar release/
        cd release
        zip ${VERSION}.zip *.jar
      shell: bash

    - name: Upload release artifact
      uses: actions/upload-artifact@v3
      with:
        name: release
        path: release/*.zip

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release Candidate ${{ github.ref }}
        draft: false
        prerelease: true
        generate_release_notes: true

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/*.zip
        asset_name: ${{ github.ref }}.zip
        asset_content_type: application/zip
