name: Java CI

on: [push]

jobs:
  build:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode package
    - name: Testing with Maven
      run: mvn test
      
    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v3
      with: 
        name: build-result
        path: ./target/Comasy-0.0.1-SNAPSHOT.jar

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: 'build-'
