name: Build develop tag with Maven

on:
  push:
    branches: main
  pull_request:
    branches: main
    types: closed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode package

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent
          verify org.jacoco:jacoco-maven-plugin:report
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=mirnamedeiros_GCM-Sistema-Bancario

      - name: Testing with Maven
        run: mvn test

      - name: Package build
        run: zip -r "${{ github.ref_name }}.zip" target/*.jar

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.ref_name }}
          path: "${{ github.ref_name }}.zip"
